version: '3.9'
services:
  db:
    container_name: MariaDB
    image: mariadb:10.6
    volumes:
        - "./conf.d:/etc/mysql/conf.d"
        - "./data:/var/lib/mysql"
    environment:
        MARIADB_DATABASE: project
        MARIADB_USER: admin
        MARIADB_PASSWORD: test123
        MARIADB_ROOT_PASSWORD: test123
    ports:
        - "3306:3306"
    restart: always

